fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: forge-fmt
        name: forge fmt
        description: Format files with solidity fmt.
        entry: bash -c 'forge fmt'
        language: rust
        files: \.sol$
        args: []
      - id: typos
        name: typos
        description: check typo
        entry: bash -c 'typos'
        language: rust
        files: \.*$
        pass_filenames: false
      - id: forge-test
        name: test test
        description: unit test for the project
        entry: bash -c 'forge test -vvv'
        language: rust
        files: \.sol$
        pass_filenames: false
